# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  # Runs on pushes 
  push:
  # and run on a schedule
  schedule: 
    # for those that don't speak cron, this runs 42 minutes past the hour, every hour
    - cron: '42 0-23 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, and cancel any in-progress deployments if a new one is triggered
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          # Using fetch-depth: 0 to ensure we get the full history of the repository
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@main
      - name: Build Pages
        shell: pwsh
        run: ./MrPowerShell.com/build.ps1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          # Upload the contents of the ./MrPowerShell.com directory to the GitHub Pages artifact
          path: './MrPowerShell.com/'          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
